clusters:
  parent:
    aws_account_name: sportsbook-cert
    aws_region: us-east-2
    environment_name: fbg-cert-1
  dbz:
    aws_account_name: sportsbook-cert
    aws_region: us-east-2
    environment_name: fbg-cert-1-debezium-1
  data:
    aws_account_name: sportsbook-cert
    aws_region: us-east-2
    environment_name: fbg-cert-1-data-1
  c:
    aws_account_name: sportsbook-cert-child-1
    aws_region: us-east-2
    environment_name: fbg-cert-1c
  tn:
    aws_account_name: sportsbook-cert-child-tn-1
    aws_region: us-east-1
    environment_name: fbg-cert-1tn
  va:
    aws_account_name: sportsbook-cert-child-va-1
    aws_region: us-east-1
    environment_name: fbg-cert-1va
  oh:
    aws_account_name: sportsbook-cert-child-oh-1
    aws_region: us-east-2
    environment_name: fbg-cert-1oh
  ma:
    aws_account_name: sportsbook-cert-child-ma-1
    aws_region: us-east-1
    environment_name: fbg-cert-1ma
  md:
    aws_account_name: sportsbook-cert-child-md-1
    aws_region: us-east-1
    environment_name: fbg-cert-1md
  mi:
    aws_account_name: sportsbook-cert-child-mi-1
    aws_region: us-east-2
    environment_name: fbg-cert-1mi
  co:
    aws_account_name: sportsbook-cert-child-co-1
    aws_region: us-east-2
    environment_name: fbg-cert-1co
  pa:
    aws_account_name: sportsbook-cert-child-pa-1
    aws_region: us-east-1
    environment_name: fbg-cert-1pa
  nj:
    aws_account_name: sportsbook-cert-child-nj-1
    aws_region: us-east-1
    environment_name: fbg-cert-1nj
  ks:
    aws_account_name: sportsbook-cert-child-ks-1
    aws_region: us-east-2
    environment_name: fbg-cert-1ks
  ky:
    aws_account_name: sportsbook-cert-child-ky-1
    aws_region: us-east-2
    environment_name: fbg-cert-1ky
  wv:
    aws_account_name: sportsbook-cert-child-wv-1
    aws_region: us-east-1
    environment_name: fbg-cert-1wv
  ct:
    aws_account_name: sportsbook-cert-child-ct-1
    aws_region: us-east-1
    environment_name: fbg-cert-1ct
  nc:
    aws_account_name: sportsbook-cert-child-nc-1
    aws_region: us-east-1
    environment_name: fbg-cert-1nc
  ia:
    aws_account_name: sportsbook-cert-child-ia-1
    aws_region: us-east-2
    environment_name: fbg-cert-1ia
  ny:
    aws_account_name: sportsbook-cert-child-ny-1
    aws_region: us-east-1
    environment_name: fbg-cert-1ny
  vt:
    aws_account_name: sportsbook-cert-child-vt-1
    aws_region: us-east-1
    environment_name: fbg-cert-1vt
  il:
    aws_account_name: sportsbook-cert-child-il-1
    aws_region: us-east-2
    environment_name: fbg-cert-1il
  in:
    aws_account_name: sportsbook-cert-child-in-1
    aws_region: us-east-2
    environment_name: fbg-cert-1in
  az:
    aws_account_name: sportsbook-cert-child-az-1
    aws_region: us-east-2
    environment_name: fbg-cert-1az
  wy:
    aws_account_name: sportsbook-cert-child-wy-1
    aws_region: us-east-2
    environment_name: fbg-cert-1wy
  la:
    aws_account_name: sportsbook-cert-child-la-1
    aws_region: us-east-2
    environment_name: fbg-cert-1la
  dc:
    aws_account_name: sportsbook-cert-child-dc-1
    aws_region: us-east-1
    environment_name: fbg-cert-1dc
stage: cert
