clusters:
  parent:
    aws_account_name: sportsbook-dev
    aws_region: us-west-2
    environment_name: fbg-dev-1
  dbz:
    aws_account_name: sportsbook-dev
    aws_region: us-west-2
    environment_name: fbg-dev-1-debezium-1
  data:
    aws_account_name: sportsbook-dev
    aws_region: us-west-2
    environment_name: fbg-dev-1-data-1
  c:
    aws_account_name: sportsbook-va-1-dev
    aws_region: us-east-2
    environment_name: fbg-dev-1c
  nj:
    aws_account_name: sportsbook-dev-child-nj-1
    aws_region: us-east-2
    environment_name: fbg-dev-1nj
stage: dev
