clusters:
  parent:
    aws_account_name: sportsbook-inf-dev
    aws_region: us-east-2
    environment_name: fbg-inf-dev-1
  dbz:
    aws_account_name: sportsbook-inf-dev
    aws_region: us-east-2
    environment_name: fbg-inf-dev-1-debezium-1
  data:
    aws_account_name: sportsbook-inf-dev
    aws_region: us-east-2
    environment_name: fbg-inf-dev-1-data-1
  tn:
    aws_account_name: sportsbook-inf-dev-child-tn-1
    aws_region: us-east-2
    environment_name: fbg-inf-dev-1tn
  nj:
    aws_account_name: sportsbook-inf-dev-child-nj-1
    aws_region: us-east-2
    environment_name: fbg-inf-dev-1nj
stage: inf-dev
