clusters:
  parent:
    environment_name: fbg-local-1
    roles:
      primary:
        endpoint: "127.0.0.1"
        port: 7432
        instance_name: fbg-local-parent-1
  dbz:
    environment_name: fbg-local-1-debezium
    roles:
      primary:
        endpoint: "127.0.0.1"
        port: 6432
        instance_name: fbg-local-debezium-parent-1
  data:
    environment_name: fbg-local-1-data
    roles:
      primary:
        endpoint: "127.0.0.1"
        port: 4432
        instance_name: fbg-local-data-parent-1
  1c:
    environment_name: fbg-local-1c
    roles:
      primary:
        endpoint: "127.0.0.1"
        port: 8432
        instance_name: fbg-local-child-1
  2c:
    environment_name: fbg-local-2c
    roles:
      primary:
        endpoint: "127.0.0.1"
        port: 9432
        instance_name: fbg-local-child-2
  nj:
    environment_name: fbg-local-nj
    roles:
      primary:
        endpoint: "127.0.0.1"
        port: 9532
        instance_name: fbg-local-child-nj
stage: local