clusters:
  parent:
    aws_account_name: sportsbook-prod
    aws_region: us-east-2
    environment_name: fbg-prod-1
  dbz:
    aws_account_name: sportsbook-prod
    aws_region: us-east-2
    environment_name: fbg-prod-1-debezium-1
  data:
    aws_account_name: sportsbook-prod
    aws_region: us-east-2
    environment_name: fbg-prod-1-data-1
  az:
    aws_account_name: sportsbook-prod-child-az-1
    aws_region: us-east-2
    environment_name: fbg-prod-1az
  tn:
    aws_account_name: sportsbook-prod-child-tn-1
    aws_region: us-east-1
    environment_name: fbg-prod-1tn
  va:
    aws_account_name: sportsbook-prod-child-va-1
    aws_region: us-east-1
    environment_name: fbg-prod-1va
  oh:
    aws_account_name: sportsbook-prod-child-oh-1
    aws_region: us-east-2
    environment_name: fbg-prod-1oh
  ma:
    aws_account_name: sportsbook-prod-child-ma-1
    aws_region: us-east-1
    environment_name: fbg-prod-1ma
  md:
    aws_account_name: sportsbook-prod-child-md-1
    aws_region: us-east-1
    environment_name: fbg-prod-1md
  co:
    aws_account_name: sportsbook-prod-child-co-1
    aws_region: us-east-2
    environment_name: fbg-prod-1co
  ky:
    aws_account_name: sportsbook-prod-child-ky-1
    aws_region: us-east-2
    environment_name: fbg-prod-1ky
  wv:
    aws_account_name: sportsbook-prod-child-wv-1
    aws_region: us-east-1
    environment_name: fbg-prod-1wv
  ct:
    aws_account_name: sportsbook-prod-child-ct-1
    aws_region: us-east-1
    environment_name: fbg-prod-1ct
  nc:
    aws_account_name: sportsbook-prod-child-nc-1
    aws_region: us-east-1
    environment_name: fbg-prod-1nc
  nj:
    aws_account_name: sportsbook-prod-child-nj-1
    aws_region: us-east-1
    environment_name: fbg-prod-1nj
  mi:
    aws_account_name: sportsbook-prod-child-mi-1
    aws_region: us-east-2
    environment_name: fbg-prod-1mi
  pa:
    aws_account_name: sportsbook-prod-child-pa-1
    aws_region: us-east-1
    environment_name: fbg-prod-1pa
  il:
    aws_account_name: sportsbook-prod-child-il-1
    aws_region: us-east-2
    environment_name: fbg-prod-1il
  vt:
    aws_account_name: sportsbook-prod-child-vt-1
    aws_region: us-east-1
    environment_name: fbg-prod-1vt
  in:
    aws_account_name: sportsbook-prod-child-in-1
    aws_region: us-east-2
    environment_name: fbg-prod-1in
  ny:
    aws_account_name: sportsbook-prod-child-ny-1
    aws_region: us-east-1
    environment_name: fbg-prod-1ny
  ia:
    aws_account_name: sportsbook-prod-child-ia-1
    aws_region: us-east-2
    environment_name: fbg-prod-1ia
  ks:
    aws_account_name: sportsbook-prod-child-ks-1
    aws_region: us-east-2
    environment_name: fbg-prod-1ks
  wy:
    aws_account_name: sportsbook-prod-child-wy-1
    aws_region: us-east-2
    environment_name: fbg-prod-1wy
  la:
    aws_account_name: sportsbook-prod-child-la-1
    aws_region: us-east-2
    environment_name: fbg-prod-1la
  dc:
    aws_account_name: sportsbook-prod-child-dc-1
    aws_region: us-east-1
    environment_name: fbg-prod-1dc
stage: prod
