clusters:
  parent:
    aws_account_name: sportsbook-test
    aws_region: us-east-2
    environment_name: fbg-test-1
  dbz:
    aws_account_name: sportsbook-test
    aws_region: us-east-2
    environment_name: fbg-test-1-debezium-1
  data:
    aws_account_name: sportsbook-test
    aws_region: us-east-2
    environment_name: fbg-test-1-data-1
  c:
    aws_account_name: sportsbook-test-child-1
    aws_region: us-east-2
    environment_name: fbg-test-1c
  tn:
    aws_account_name: sportsbook-test-child-tn-1
    aws_region: us-east-1
    environment_name: fbg-test-1tn
  nj:
    aws_account_name: sportsbook-test-child-nj-1
    aws_region: us-east-1
    environment_name: fbg-test-1nj
stage: test
